name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: elevantiq/pg-backup

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - pg_version: "14"
            alpine_version: "3.16"
          - pg_version: "15"
            alpine_version: "3.17"
          - pg_version: "16"
            alpine_version: "3.19"
            latest: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=pg${{ matrix.pg_version }}
            type=raw,value=latest,enable=${{ matrix.latest == true }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
            PG_VERSION=${{ matrix.pg_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
